services:
  - type: web
    name: my-flask-app
    repo: https://github.com/HishitaGupta/EdTechChatbot
    branch: main
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    instanceType: free
